version: '3'
services:
  finances-app-db:
    container_name: finances-app-db
    image: postgres:13.4-alpine
    environment:
      - 'POSTGRES_DB=finances_app'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'